version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat8-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/database/chat8.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
    volumes:
      - ./data:/app/data
      - ./backend/app:/app/app
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - chat8-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat8-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - chat8-network

  # Redis 缓存服务（可选）
  redis:
    image: redis:7-alpine
    container_name: chat8-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - chat8-network

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: chat8-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - chat8-network

volumes:
  redis_data:

networks:
  chat8-network:
    driver: bridge